### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by deavmi** [pjuu/pjuu#74]
These are some of my ideas for **Pjuu**.

- [ ] ~~Click-able and viewable full-size profile picture (from clicking the profile picture from the user's profile page)~~ Will fix in #104
- [ ] ~~Sound on new alert~~ (Not going to implement, as the method should be thought about on all platform and we need an API and the likes first)
- [ ] ~~Direct Messaging~~ #107 
- [ ] ~~Posts per Feed page selection~~ will add in #106
- [ ] ~~The ability to choose how many alerts there are on the notifications page.~~ #106
- [ ] ~~Un-doing an upvote or downvote~~ see #85
- [ ] ~~Blocking of users~~ (will roll in to #46)
- [ ] ~~Hashtags~~ (https://github.com/pjuu/pjuu/issues/53)
- [ ] ~~Groups~~ wont add.
- [ ] ~~Maybe `Ctrl`+`Enter` to submit a post~~ Up to your browser
- [ ] ~~Maybe bulk deletion of posts~~ I think post deletion should be thought about, just as post creation.
- [ ] ~~Daily digest email (Of alerts that happened in one single day)~~ We don't want to spam. Not a mailing list
- [ ] ~~Data import feature (the opposite of the already existing data export feature or **data dump**)~~ Far to many privacy/security concerns. People could duplicate accounts with web scraping
- [ ] ~~Clear all notifications~~ see #67
- [ ] ~~A clear notification system that actually deletes the notifications~~ Not possible due to nature of them see #67
- [ ] ~~Overview, part of the text in the notification~~ Not plausible.
- [ ] ~~Date of user's registration~~
- [ ] [More preferences](https://github.com/pjuu/pjuu/issues/75) in the settings area
- [x] I think that if a post was made and it notifies the user of that post but then the post is deleted, then the alert item should be removed form the alerts list/page
- [ ] ~~Once on the profile page, if the end-user clicks on the profile picture of the profile he is viewing it should then open up that profile picture direvctly (URL).~~ #104

**Comment by deavmi** [comment]
Email alerts would be great.

**Comment by Walkman100** [comment]
@deavmi you should expand that last point, more preferences, into the two on the referenced issue.

**Comment by deavmi** [comment]
@deavmi Will do that soon, need to quickly finish some of my BoaGen stuff, then I will get back to Pjuu.

**Comment by pjuu** [comment]
@deavmi please can you expand on "Alerts per Alerts page selection"?

**Comment by deavmi** [comment]
The ability to choose how many alerts there are on the notifications page.

**Comment by pjuu** [comment]
Okay. That will come in when setting the length of pagination objects is added.

**Comment by pjuu** [comment]
@deavmi Can you please expand on " I think that if a post was made and it notifies the user of that post but then the post is deleted, then the alert item should be removed form the alerts list/page"? This should already be happening due to verify() methods on alerts.

https://github.com/pjuu/pjuu/blob/master/pjuu/lib/alerts.py#L91-L98

Each alert type implements it's own verify().

You may still see the alert icon turn red however if it there on a page reload or js poll. This happens because once it has found an alert it stops polling as to not waste bandwidth for us and the user.

If this is what you mean I think it is a small price to pay. We can address this in #67 if it isn't the case.

**Comment by deavmi** [comment]
That is EXACTlY what I meant :).

**Comment by Walkman100** [comment]
@deavmi Well he talked about two different things... which of the two were 'exactiy' what you meant?

**Comment by deavmi** [comment]
Add a feature of which can display on a post the date and time of when it was posted.

**Comment by pjuu** [comment]
Opened issue #85 relating to undo votes.

**Comment by docapotamus** [comment]
I have created issues for the ideas that will be implementing from this. Thanks @deavmi, I'm going to close this issue, I have added links to the new issues.

**Comment by deavmi** [comment]
@Joe it's a pleasure. :cake: :smile_cat:

**Comment by deavmi** [comment]
Pleasure ;)
